[package]
name = "centurion"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
error-stack = "0.3"
thiserror = "1.0"
validator = { version = "0.16", features = ["derive"] }
